# Generated by Django 2.0.1 on 2018-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raduis',
            fields=[
                ('pub_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='报障时间')),
                ('bars_ip', models.GenericIPAddressField(verbose_name='接入设备')),
                ('account', models.CharField(max_length=17, verbose_name='用户账号')),
                ('problem', models.CharField(max_length=50, verbose_name='故障详情')),
            ],
            options={
                'verbose_name': 'Raduis日志',
                'verbose_name_plural': 'Raduis日志',
            },
        ),
        migrations.CreateModel(
            name='XiaoQuGuZhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=17, verbose_name='用户账号')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='报障时间')),
                ('bars', models.GenericIPAddressField(verbose_name='接入设备')),
            ],
            options={
                'verbose_name': '小区故障',
                'verbose_name_plural': '小区故障',
            },
        ),
    ]
